### ISSUE TITLE
插件周赛替换图标貌似失效了

### ISSUE THREAD

**Issue by yangeee** [XYShaoKang/refined-leetcode#5]
看了下service worker中预测网站的接口503了，力扣的接口倒是好的，但是图标没替换。

![image](https://user-images.githubusercontent.com/23137277/170939505-20806000-ad7f-4196-b63f-8a4e0f6cc52e.png)

**Comment by XYShaoKang** [comment]
应该是之前预测数据的 API 挂了,导致一直卡着,连带着替换图标的逻辑也没走下去,现在预测数据的 API 好了,应该是正常了.
后面我再找时间修一下,把这两个逻辑分开来.
