### ISSUE TITLE
有可能是系统问题或浏览器问题，MacOS edges 下载之后插件会被自动删除

### ISSUE THREAD

**Issue by volmodaoist** [XYShaoKang/refined-leetcode#7]
下载 crx 文件会被自动删除，下载压缩包之后一经解压，文件也会被立即删除…
不过科学上网之后，再用谷歌商店下载转到 edges 便没有这种问题了…

**Comment by XYShaoKang** [comment]
额，之前也有人遇到过这个问题，所以在打包的时候，我加了个 .crx.zip 的文件，下载这个文件在解压，里面就是 crx 文件了。

![2023-01-18_23-16-24](https://user-images.githubusercontent.com/38753204/213209769-883098ab-6d86-4d30-8c48-4f5e990d495a.png)
