### ISSUE TITLE
使用反馈

### ISSUE THREAD

**Issue by Zhangyu-0427** [XYShaoKang/refined-leetcode#8]
作者您好，我使用您的力扣插件有一段时间了。
在这两天更新到了最新版，在接下来的使用过程中，出现了一个比较大的问题，在我使用插件配合力扣刷题的时候，页面在进行一些交换（查看题解、评论等等）的过程中会卡死，这让我不得不关闭整个浏览器，再重新打开，非常影响刷题效率，希望作者在日后可以优化这方面的体验。

**Comment by XYShaoKang** [comment]
你好，感谢反馈。

为了方便定位问题，是否方便告知以下信息？

你有没有尝试过在关闭扩展的情况，是否会发生这种问题的呢？

如果关闭之后，问题就消失，那么有可能确实是扩展造成的，能提供下你发生问题时所使用的操作系统和浏览器的信息么？我方便去测试一下，看看能不能复现。

另外我发布了新版本，你可以尝试一下新版本是否还会出现这样的问题。

> 在线安装的版本还在等谷歌商店更新，如果有需要可以通过[离线安装](https://github.com/XYShaoKang/refined-leetcode#%E7%A6%BB%E7%BA%BF%E5%AE%89%E8%A3%85)的方式尝试。

**Comment by Zhangyu-0427** [comment]
已经用了更新后的插件 目前已经没有这种情况了









      发自我的企业微信         

 
 
 ----------回复的邮件信息----------
 ***@***.***&gt; 于2023年1月31日(周二) 上午8:06写道:

  

 
你好，感谢反馈。
 
为了方便定位问题，是否方便告知以下信息？
 
你有没有尝试过在关闭扩展的情况，是否会发生这种问题的呢？
 
如果关闭之后，问题就消失，那么有可能确实是扩展造成的，能提供下你发生问题时所使用的操作系统和浏览器的信息么？我方便去测试一下，看看能不能复现。
 
另外我发布了新版本，你可以尝试一下新版本是否还会出现这样的问题。
  
在线安装的版本还在等谷歌商店更新，如果有需要可以通过离线安装的方式尝试。
